name: Continuous integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  tests:
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-11, windows-2019 ] # list of os: https://github.com/actions/virtual-environments
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - run: git submodule update --init --recursive --force
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Install dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt update && sudo apt install build-essential
          fi
        shell: bash
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ matrix.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Lint
        if: matrix.os == 'ubuntu-20.04'
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42
          skip-go-installation: true
          skip-pkg-cache: true
          skip-build-cache: true
      - name: Install deps
        if: matrix.os == 'windows-2019'
        run: choco upgrade mingw cmake -y --no-progress
      - run: go test ./...


